# Generated by Django 4.1 on 2022-09-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('responses', models.CharField(default='', max_length=9000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='formulaire.formulaire')),
            ],
        ),
    ]
