# Generated by Django 4.1 on 2022-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='statut',
            field=models.CharField(default='En cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
